// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.srcmorph.provider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import lombok.ToString;
import net.ladenthin.llama.args.CacheType;
import net.ladenthin.llama.args.LazyMode;
import net.ladenthin.llama.parameters.InferenceParameters;
import net.ladenthin.llama.value.ChatResponse;
import net.ladenthin.llama.value.Pair;
import net.ladenthin.llama.value.Usage;
import net.ladenthin.srcmorph.document.AiGenerationRequest;
import net.ladenthin.srcmorph.prompt.AiPromptSupport;
import net.ladenthin.srcmorph.support.Java8CompatibilityHelper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Everything {@link LlamaCppJniAiGenerationProvider} does that does not touch the JNI binding's
 * native side: turning a {@link AiGenerationRequest} plus a {@link LlamaCppJniConfig} into
 * {@link InferenceParameters}, resolving configured CLI strings to the binding's enums, and
 * reporting on a {@link ChatResponse} that has already come back.
 *
 * <p><b>Why this is a class of its own.</b> It is not a style preference; it is what makes the
 * mutation gate reach these lines at all. PIT re-runs every test covering a mutated line, and while
 * this logic sat next to {@code model()} the only way to put any of it on {@code targetClasses} was
 * to put {@code model()} there too -- a ~100-line {@code ModelParameters} chain whose sole exerciser
 * is {@code LlamaCppJniKnobSweepTest}, 36 cases that each load a GGUF. Excluding those tests instead
 * does not work either: {@code model()}'s mutants then have no coverage at all, and a
 * {@code NO_COVERAGE} mutant fails a threshold-100 gate exactly like a survivor. Separating the pure
 * half is the only arrangement where the gated class is covered end to end by tests that need no
 * model, which is why the split runs along "touches the native handle" and not along any tidier
 * conceptual line.</p>
 *
 * <p>That gap was not hypothetical. The {@code dry_penalty_last_n} regression in 1.1.0/1.1.1 killed
 * every generation before a token was produced, and the gate read a stable 775/775 straight through
 * it and through its fix -- because the class generated no mutants, neither the defect nor the tests
 * that now cover it could move the number. Stability was never evidence of anything here.</p>
 *
 * <p>Members are package-private: the provider is the only production caller, and the tests live in
 * this package. {@code toString} is generated by Lombok for build-log diagnostics.</p>
 */
@ToString
final class LlamaCppJniProviderSupport {

    private static final Logger LOGGER = LoggerFactory.getLogger(LlamaCppJniProviderSupport.class);

    /** OpenAI finish reason meaning "the token budget ran out", as opposed to {@code "stop"}. */
    private static final String FINISH_REASON_LENGTH = "length";

    /**
     * Fixed llama.cpp server slot every request is pinned to. The model is loaded once and reused
     * for all files; pinning each request to the same slot lets the prompt cache
     * ({@code cache_prompt}) reuse the shared prompt-template prefix's KV across files instead of
     * re-prefilling it for every file. Reuse is exact, so generated output is unchanged.
     */
    private static final int REUSE_SLOT_ID = 0;

    /** Chat-template kwarg controlling Qwen-style thinking (ignored by non-Qwen templates). */
    private static final String ENABLE_THINKING_KWARG = "enable_thinking";

    /** Chat-template kwarg for the gpt-oss reasoning-effort level (ignored by non-gpt-oss templates). */
    private static final String REASONING_EFFORT_KWARG = "reasoning_effort";

    /** Number of chat-template kwargs put into the map (used for presizing). */
    private static final int CHAT_TEMPLATE_KWARG_COUNT = 2;

    private final LlamaCppJniConfig config;
    private final AiPromptSupport promptSupport;
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    /**
     * Creates the support object for one provider instance.
     *
     * @param config        llama.cpp configuration
     * @param promptSupport prompt lookup used to render request prompts
     */
    LlamaCppJniProviderSupport(final LlamaCppJniConfig config, final AiPromptSupport promptSupport) {
        this.config = Objects.requireNonNull(config, "config");
        this.promptSupport = Objects.requireNonNull(promptSupport, "promptSupport");
    }

    /**
     * Builds the chat-template kwargs passed to
     * {@link net.ladenthin.llama.parameters.ModelParameters#setChatTemplateKwargs}.
     *
     * <p>Both kwargs are opt-in: an entry is written only when the user actually configured it, so a
     * chat template that has never heard of the kwarg is not handed it. That matters because
     * llama.cpp's Jinja layer has been moving unknown kwargs from "silently ignored" toward "warned
     * about" -- while {@code enable_thinking} was a plain {@code boolean} defaulting to {@code true},
     * every run sent it, and the only way to stop the noise was to set the knob to {@code false},
     * which means something else entirely.</p>
     *
     * @return the kwargs to send; empty when neither knob is configured
     */
    Map<String, String> buildChatTemplateKwargs() {
        final Map<String, String> chatTemplateKwargs =
                new HashMap<>(compatibilityHelper.hashMapCapacityFor(CHAT_TEMPLATE_KWARG_COUNT));
        // Qwen-style thinking. Unset (null) omits the kwarg so the model's own template default applies.
        final Boolean enableThinking = config.chatTemplateEnableThinking();
        if (enableThinking != null) {
            chatTemplateKwargs.put(ENABLE_THINKING_KWARG, String.valueOf(enableThinking.booleanValue()));
        }
        // gpt-oss honors reasoning_effort; non-gpt-oss chat templates ignore it. An empty
        // configured value omits the kwarg so the model's own template default applies.
        if (!compatibilityHelper.isBlank(config.reasoningEffort())) {
            chatTemplateKwargs.put(REASONING_EFFORT_KWARG, config.reasoningEffort());
        }
        return chatTemplateKwargs;
    }

    /**
     * Resolves a configured {@code --lazy-mode} value to the binding's enum.
     *
     * <p>Matched case-insensitively against the CLI strings the enum itself declares
     * ({@code off}, {@code auto}, {@code on}), so this never drifts from the binding. An
     * unrecognised value is rejected rather than silently ignored: it is always a configuration
     * typo, and dropping it would hand the user a run that quietly did not do what was asked.</p>
     *
     * @param value the configured value; must not be blank (callers guard on that)
     * @return the matching mode
     * @throws IllegalArgumentException if no mode declares that CLI string
     */
    static LazyMode lazyMode(final String value) {
        for (final LazyMode mode : LazyMode.values()) {
            if (mode.getArgValue().equalsIgnoreCase(value)) {
                return mode;
            }
        }
        throw new IllegalArgumentException(
                "Invalid lazyMode value: \"" + value + "\" (expected one of: " + knownLazyModeValues() + ")");
    }

    /**
     * Resolves a configured {@code --cache-type-k} / {@code --cache-type-v} value to the binding's enum.
     *
     * <p>Same contract as {@link #lazyMode(String)}: matched case-insensitively against the CLI
     * strings the enum itself declares, so a cache type upstream adds is accepted for free, and an
     * unrecognised value is rejected rather than dropped. The knob name is passed in so the message names
     * the element the user actually wrote.</p>
     *
     * @param knobName the configuration element name, for the error message
     * @param value    the configured value; must not be blank (callers guard on that)
     * @return the matching cache type
     * @throws IllegalArgumentException if no cache type declares that CLI string
     */
    static CacheType cacheType(final String knobName, final String value) {
        for (final CacheType type : CacheType.values()) {
            if (type.getArgValue().equalsIgnoreCase(value)) {
                return type;
            }
        }
        throw new IllegalArgumentException(
                "Invalid " + knobName + " value: \"" + value + "\" (expected one of: " + knownCacheTypeValues() + ")");
    }

    /**
     * Renders the accepted KV-cache types for an error message.
     *
     * @return the CLI strings the binding's enum declares, comma-separated in declaration order
     */
    private static String knownCacheTypeValues() {
        final StringBuilder known = new StringBuilder();
        for (final CacheType type : CacheType.values()) {
            if (known.length() > 0) {
                known.append(", ");
            }
            known.append(type.getArgValue());
        }
        return known.toString();
    }

    /**
     * Renders the accepted {@code --lazy-mode} values for an error message.
     *
     * @return the CLI strings the binding's enum declares, comma-separated in declaration order
     */
    private static String knownLazyModeValues() {
        final StringBuilder known = new StringBuilder();
        for (final LazyMode mode : LazyMode.values()) {
            if (known.length() > 0) {
                known.append(", ");
            }
            known.append(mode.getArgValue());
        }
        return known.toString();
    }

    /**
     * Warns when the model stopped because the output budget ran out rather than because it was done.
     *
     * @param request  the request whose source file is named in the warning
     * @param response the completed chat response
     */
    void warnOnTruncatedAnswer(final AiGenerationRequest request, final ChatResponse response) {
        if (response.getChoices().isEmpty()) {
            return;
        }
        if (!FINISH_REASON_LENGTH.equals(response.getChoices().get(0).getFinishReason())) {
            return;
        }
        LOGGER.warn(
                "Generated text for {} was cut off at the {}-token output budget, not finished by the model."
                        + " The .ai.md will end mid-thought; raise maxOutputTokens for this model, or shorten"
                        + " the prompt.",
                request.sourceFile(),
                config.maxOutputTokens());
    }

    /**
     * Reports how much of the prompt was served from the KV cache, at debug level.
     *
     * @param request  the request whose source file is named in the line
     * @param response the completed chat response
     */
    void logPromptCacheReuse(final AiGenerationRequest request, final ChatResponse response) {
        if (!LOGGER.isDebugEnabled()) {
            return;
        }
        // No null guard: ChatResponse.getUsage() is declared non-null, and SpotBugs flags a check on it
        // as dead code (RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE). Unlike getTimings(), which the
        // timings path does have to guard.
        final Usage usage = response.getUsage();
        LOGGER.debug(
                "{}: {} of {} prompt token(s) served from the KV cache, {} generated",
                request.sourceFile(),
                usage.getCachedTokens(),
                usage.getPromptTokens(),
                usage.getCompletionTokens());
    }

    /**
     * Builds the per-request inference parameters from the configuration and the request.
     *
     * @param request the request to render
     * @return the parameters to hand to the binding
     */
    InferenceParameters buildInferenceParameters(final AiGenerationRequest request) {
        // Static instructions go in the SYSTEM message (byte-identical across files, so its KV
        // prefix is reused by cache_prompt); the variable file name + source go in the USER message.
        final String systemPrompt = promptSupport.systemPrompt(request.promptKey());
        final String userMessage = promptSupport.userMessage(request.sourceFile(), request.sourceText());
        final List<Pair<String, String>> messages = new ArrayList<>();
        messages.add(new Pair<>("user", userMessage));
        // InferenceParameters uses immutable withers: each with* returns a new instance, so the
        // whole request is built as a single chain.
        final InferenceParameters baseParameters = new InferenceParameters("")
                .withMessages(systemPrompt, messages)
                .withTemperature(config.temperature())
                .withNPredict(config.maxOutputTokens())
                .withTopP(config.topP())
                .withTopK(config.topK())
                .withMinP(config.minP())
                .withTopNSigma(config.topNSigma())
                .withRepeatPenalty(config.repeatPenalty())
                // Cap harmony analysis (reasoning) tokens so a runaway chain-of-thought cannot
                // starve the final answer; -1 (default) = unrestricted, so behaviour is unchanged.
                .withReasoningBudgetTokens(config.reasoningBudgetTokens())
                // DRY (Don't Repeat Yourself) repetition suppression; multiplier 0.0 (default) = off,
                // so the base/allowed-length knobs have no effect unless opted in. The DRY penalty
                // WINDOW is deliberately not in this chain -- see penaltyScopedParameters below.
                .withDryMultiplier(config.dryMultiplier())
                .withDryBase(config.dryBase())
                .withDryAllowedLength(config.dryAllowedLength())
                .withStopStrings(config.stopStrings().toArray(new String[0]))
                // Keep the shared prompt-template prefix warm in the KV cache and reuse it across
                // files (pinned to one slot); only the differing source is re-prefilled.
                // Reuse is exact -> output unchanged.
                .withCachePrompt(config.cachePrompt())
                .withSlotId(REUSE_SLOT_ID);
        // Pin the RNG seed only when explicitly configured (>= 0). Upstream's default is a random seed
        // per request, so an unconfigured run keeps exactly the behaviour it had; a configured one makes
        // the generated body stable for a given machine and configuration, which is what turns a
        // re-index into a reviewable diff. Not bit-reproducibility -- see AiGenerationConfig.DEFAULT_SEED.
        final InferenceParameters seededParameters =
                config.seed() >= 0 ? baseParameters.withSeed(config.seed()) : baseParameters;
        // The two penalty windows -- the one the repeat penalty acts on, and DRY's own -- are forwarded
        // only when configured (>= 0), so an unconfigured run keeps llama.cpp's own window; 0 is
        // meaningful (disables the penalty), which is why the guard is >= 0 rather than > 0.
        //
        // The guard is not an optimisation, it is the only thing keeping the provider alive. The binding
        // REJECTS a negative window outright (IllegalArgumentException, because llama.cpp b10273 dropped
        // "-1 = context size"), and both defaults are -1. An unguarded forward therefore kills EVERY
        // generation before a token is produced, whatever the rest of the configuration says. That is
        // not hypothetical: dryPenaltyLastN was forwarded unguarded and did exactly that in 1.1.0 and
        // 1.1.1. It survived because "DRY is off by default, so the window cannot matter" is true of the
        // window's *effect* and false of the setter's *validation* -- the wither rejects the value
        // whether or not DRY is active. Keep both guards, and add one for any future knob whose sentinel
        // is negative.
        final InferenceParameters repeatScopedParameters =
                config.repeatLastN() >= 0 ? seededParameters.withRepeatLastN(config.repeatLastN()) : seededParameters;
        final InferenceParameters penaltyScopedParameters = config.dryPenaltyLastN() >= 0
                ? repeatScopedParameters.withDryPenaltyLastN(config.dryPenaltyLastN())
                : repeatScopedParameters;
        // Only override the DRY sequence breakers when explicitly configured; an empty list keeps
        // the binding/model default set instead of clearing it.
        return config.drySequenceBreakers().isEmpty()
                ? penaltyScopedParameters
                : penaltyScopedParameters.withDrySequenceBreakers(
                        config.drySequenceBreakers().toArray(new String[0]));
    }
}
