// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.srcmorph.provider;

import java.util.Collections;
import java.util.List;
import java.util.Objects;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import net.ladenthin.srcmorph.config.AiGenerationConfig;
import net.ladenthin.srcmorph.support.ConvertToRecord;
import org.jspecify.annotations.Nullable;

/**
 * Immutable configuration for the llama.cpp JNI provider.
 *
 * <p>Built through {@link #builder(String)}; the positional constructor is private (thirty-seven
 * arguments is past the point where a call site is readable or a swapped pair is noticeable).</p>
 *
 * <p>Record-shaped value type marked {@link net.ladenthin.srcmorph.support.ConvertToRecord} for the future Java&nbsp;17+
 * migration. Accessors are record-style. {@code equals}, {@code hashCode} and
 * {@code toString} are generated by Lombok over all thirty-seven fields; full value semantics
 * apply. Lombok emits the exact-bit float comparison
 * ({@code Float.floatToIntBits}) automatically.</p>
 */
@ConvertToRecord
@ToString
@EqualsAndHashCode
public final class LlamaCppJniConfig {
    private final String modelPath;
    private final int contextSize;
    private final int maxOutputTokens;
    private final float temperature;
    private final int threads;
    private final float topP;
    private final int topK;
    private final float minP;
    private final float topNSigma;
    private final float repeatPenalty;
    private final @Nullable Boolean chatTemplateEnableThinking;
    private final boolean cachePrompt;
    private final boolean swaFull;
    private final int cacheReuse;
    private final int gpuLayers;
    private final int seed;
    private final int cpuMoeLayers;
    private final int cpuFfnLayers;
    private final int kvUnifiedPerSlot;
    private final String lazyMode;
    private final int repeatLastN;
    private final String cacheTypeK;
    private final String cacheTypeV;
    private final boolean flashAttn;
    private final int batchSize;
    private final int ubatchSize;
    private final int threadsBatch;
    private final int mainGpu;
    private final String devices;
    private final String reasoningEffort;
    private final int reasoningBudgetTokens;
    private final float dryMultiplier;
    private final float dryBase;
    private final int dryAllowedLength;
    private final int dryPenaltyLastN;
    private final List<String> drySequenceBreakers;
    private final List<String> stopStrings;

    /**
     * Creates a configuration from a fully populated {@link Builder}.
     *
     * <p>Private on purpose: with thirty-seven fields a positional constructor is unreadable at the call
     * site and a swap of two same-typed neighbours compiles silently. {@link #builder(String)} is the only
     * way in, so every value arrives named, and every value the caller did not name is the matching
     * {@code AiGenerationConfig.DEFAULT_*} rather than Java's zero.</p>
     *
     * <p>No normalisation happens here — the builder's setters already did it, and duplicating a guard on
     * an unreachable path would only look like protection.</p>
     *
     * @param builder the populated builder
     */
    private LlamaCppJniConfig(final Builder builder) {
        this.modelPath = builder.modelPath;
        this.contextSize = builder.contextSize;
        this.maxOutputTokens = builder.maxOutputTokens;
        this.temperature = builder.temperature;
        this.threads = builder.threads;
        this.topP = builder.topP;
        this.topK = builder.topK;
        this.minP = builder.minP;
        this.topNSigma = builder.topNSigma;
        this.repeatPenalty = builder.repeatPenalty;
        this.chatTemplateEnableThinking = builder.chatTemplateEnableThinking;
        this.cachePrompt = builder.cachePrompt;
        this.swaFull = builder.swaFull;
        this.cacheReuse = builder.cacheReuse;
        this.gpuLayers = builder.gpuLayers;
        this.seed = builder.seed;
        this.cpuMoeLayers = builder.cpuMoeLayers;
        this.cpuFfnLayers = builder.cpuFfnLayers;
        this.kvUnifiedPerSlot = builder.kvUnifiedPerSlot;
        this.lazyMode = builder.lazyMode;
        this.repeatLastN = builder.repeatLastN;
        this.cacheTypeK = builder.cacheTypeK;
        this.cacheTypeV = builder.cacheTypeV;
        this.flashAttn = builder.flashAttn;
        this.batchSize = builder.batchSize;
        this.ubatchSize = builder.ubatchSize;
        this.threadsBatch = builder.threadsBatch;
        this.mainGpu = builder.mainGpu;
        this.devices = builder.devices;
        this.reasoningEffort = builder.reasoningEffort;
        this.reasoningBudgetTokens = builder.reasoningBudgetTokens;
        this.dryMultiplier = builder.dryMultiplier;
        this.dryBase = builder.dryBase;
        this.dryAllowedLength = builder.dryAllowedLength;
        this.dryPenaltyLastN = builder.dryPenaltyLastN;
        this.drySequenceBreakers = builder.drySequenceBreakers;
        this.stopStrings = builder.stopStrings;
    }

    /**
     * Starts building a configuration for the given model, with every other value pre-set to its
     * {@code AiGenerationConfig.DEFAULT_*}.
     *
     * <p>{@code modelPath} is the one value with no meaningful default, so it is required here rather
     * than checked in {@code build()}: a caller cannot construct a half-formed builder at all.</p>
     *
     * @param modelPath path to the GGUF model file; must not be {@code null}
     * @return a builder carrying the defaults
     * @throws NullPointerException if {@code modelPath} is {@code null}
     */
    public static Builder builder(final String modelPath) {
        return new Builder(modelPath);
    }

    /**
     * Returns the GGUF model file path.
     *
     * @return model file path
     */
    public String modelPath() {
        return modelPath;
    }

    /**
     * Returns the context window size in tokens.
     *
     * @return context window size
     */
    public int contextSize() {
        return contextSize;
    }

    /**
     * Returns the maximum number of output tokens per call.
     *
     * @return maximum output tokens
     */
    public int maxOutputTokens() {
        return maxOutputTokens;
    }

    /**
     * Returns the sampling temperature.
     *
     * @return sampling temperature
     */
    public float temperature() {
        return temperature;
    }

    /**
     * Returns the number of CPU threads.
     *
     * @return number of CPU threads
     */
    public int threads() {
        return threads;
    }

    /**
     * Returns the nucleus-sampling probability threshold.
     *
     * @return top-p value
     */
    public float topP() {
        return topP;
    }

    /**
     * Returns the top-k sampling limit.
     *
     * @return top-k value
     */
    public int topK() {
        return topK;
    }

    /**
     * Returns the min-p sampling threshold.
     *
     * @return min-p threshold ({@code 0.0} = disabled)
     */
    public float minP() {
        return minP;
    }

    /**
     * Returns the top-n-sigma sampling threshold.
     *
     * @return top-n-sigma threshold ({@code -1.0} = disabled)
     */
    public float topNSigma() {
        return topNSigma;
    }

    /**
     * Returns the repetition penalty.
     *
     * @return repeat penalty
     */
    public float repeatPenalty() {
        return repeatPenalty;
    }

    /**
     * Returns the chat-template thinking mode, or {@code null} when it was never set.
     *
     * @return {@code true} or {@code false} when the knob was set, {@code null} when it is unset
     *         &#x2014; the provider then omits the {@code enable_thinking} kwarg entirely and the
     *         model's own chat-template default applies
     * @see AiGenerationConfig#DEFAULT_CHAT_TEMPLATE_ENABLE_THINKING
     */
    public @Nullable Boolean chatTemplateEnableThinking() {
        return chatTemplateEnableThinking;
    }

    /**
     * Returns whether llama.cpp prompt caching ({@code cache_prompt}) is enabled.
     *
     * @return {@code true} when prompt-prefix KV reuse across files is enabled
     */
    public boolean cachePrompt() {
        return cachePrompt;
    }

    /**
     * Returns whether the full-size SWA KV cache is kept ({@code --swa-full}).
     *
     * @return {@code true} when full SWA KV is kept
     */
    public boolean swaFull() {
        return swaFull;
    }

    /**
     * Returns the KV prefix-reuse minimum chunk size ({@code --cache-reuse}).
     *
     * @return cache-reuse chunk size ({@code 0} = disabled)
     */
    public int cacheReuse() {
        return cacheReuse;
    }

    /**
     * Returns the number of model layers to offload to the GPU ({@code --gpu-layers}).
     *
     * @return GPU layers ({@code -1} = leave the binding/build default)
     */
    public int gpuLayers() {
        return gpuLayers;
    }

    /**
     * Returns the RNG seed used for generation.
     *
     * @return the seed ({@code -1} = leave the binding's random-per-request default)
     */
    public int seed() {
        return seed;
    }

    /**
     * Returns the number of MoE layers kept on the CPU ({@code --n-cpu-moe}).
     *
     * @return CPU MoE layers ({@code -1} = leave the binding/build default)
     */
    public int cpuMoeLayers() {
        return cpuMoeLayers;
    }

    /**
     * Returns the number of FFN layers kept on the CPU ({@code --n-cpu-ffn}).
     *
     * @return CPU FFN layers ({@code -1} = leave the binding/build default)
     */
    public int cpuFfnLayers() {
        return cpuFfnLayers;
    }

    /**
     * Returns the per-slot unified KV context cap ({@code --kv-unified-per-slot}).
     *
     * @return the cap ({@code -1} = leave the binding/build default)
     */
    public int kvUnifiedPerSlot() {
        return kvUnifiedPerSlot;
    }

    /**
     * Returns the tensor-read laziness ({@code --tensor-read-lazy}).
     *
     * @return {@code off}, {@code auto}, {@code on}, or empty to leave the binding/build default
     */
    public String lazyMode() {
        return lazyMode;
    }

    /**
     * Returns the repeat-penalty window ({@code --repeat-last-n}); {@code -1} leaves llama.cpp's own.
     *
     * @return the repeat-penalty window ({@code --repeat-last-n}); {@code -1} leaves llama.cpp's own
     */
    public int repeatLastN() {
        return repeatLastN;
    }

    /**
     * Returns the KV-cache data type for K ({@code --cache-type-k}); empty leaves the default.
     *
     * @return the KV-cache data type for K ({@code --cache-type-k}); empty leaves the default
     */
    public String cacheTypeK() {
        return cacheTypeK;
    }

    /**
     * Returns the KV-cache data type for V ({@code --cache-type-v}); empty leaves the default.
     *
     * @return the KV-cache data type for V ({@code --cache-type-v}); empty leaves the default
     */
    public String cacheTypeV() {
        return cacheTypeV;
    }

    /**
     * Returns whether Flash Attention is enabled ({@code --flash-attn}).
     *
     * @return whether Flash Attention is enabled ({@code --flash-attn})
     */
    public boolean flashAttn() {
        return flashAttn;
    }

    /**
     * Returns the logical batch size ({@code --batch-size}); {@code -1} leaves the default.
     *
     * @return the logical batch size ({@code --batch-size}); {@code -1} leaves the default
     */
    public int batchSize() {
        return batchSize;
    }

    /**
     * Returns the physical batch size ({@code --ubatch-size}); {@code -1} leaves the default.
     *
     * @return the physical batch size ({@code --ubatch-size}); {@code -1} leaves the default
     */
    public int ubatchSize() {
        return ubatchSize;
    }

    /**
     * Returns the batch/prompt-processing thread count ({@code --threads-batch}); {@code -1} reuses {@code threads}.
     *
     * @return the batch/prompt-processing thread count ({@code --threads-batch}); {@code -1} reuses {@code threads}
     */
    public int threadsBatch() {
        return threadsBatch;
    }

    /**
     * Returns the primary GPU index ({@code --main-gpu}).
     *
     * @return GPU index ({@code -1} = leave the binding/build default)
     */
    public int mainGpu() {
        return mainGpu;
    }

    /**
     * Returns the device selection ({@code --device}).
     *
     * @return comma-separated device list, or empty to leave the binding/build default
     */
    public String devices() {
        return devices;
    }

    /**
     * Returns the gpt-oss reasoning-effort kwarg value.
     *
     * @return reasoning effort ("low"/"medium"/"high"), or empty to omit the kwarg
     */
    public String reasoningEffort() {
        return reasoningEffort;
    }

    /**
     * Returns the reasoning/think-token budget.
     *
     * @return budget tokens ({@code -1} = unrestricted)
     */
    public int reasoningBudgetTokens() {
        return reasoningBudgetTokens;
    }

    /**
     * Returns the DRY sampling multiplier.
     *
     * @return DRY multiplier ({@code 0.0} = disabled)
     */
    public float dryMultiplier() {
        return dryMultiplier;
    }

    /**
     * Returns the DRY base.
     *
     * @return DRY base
     */
    public float dryBase() {
        return dryBase;
    }

    /**
     * Returns the DRY allowed length.
     *
     * @return DRY allowed length
     */
    public int dryAllowedLength() {
        return dryAllowedLength;
    }

    /**
     * Returns the DRY penalty look-back window in tokens.
     *
     * @return DRY penalty last-n ({@code -1} = not sent, llama.cpp's own window; {@code 0} = disabled)
     */
    public int dryPenaltyLastN() {
        return dryPenaltyLastN;
    }

    /**
     * Returns an unmodifiable view of the configured DRY sequence breakers.
     *
     * @return unmodifiable list of DRY sequence breakers (empty = use the binding default)
     */
    public List<String> drySequenceBreakers() {
        return Collections.unmodifiableList(drySequenceBreakers);
    }

    /**
     * Returns an unmodifiable view of the configured stop strings.
     *
     * @return unmodifiable list of stop strings
     */
    public List<String> stopStrings() {
        return Collections.unmodifiableList(stopStrings);
    }

    /**
     * Fluent builder for {@link LlamaCppJniConfig}.
     *
     * <p>Every setter is optional and starts at the matching {@code AiGenerationConfig.DEFAULT_*}, so this
     * class is the single place those defaults are applied: {@code LlamaCppJniConfigFactory}'s
     * fallback path no longer restates all thirty-six of them, and a knob added to
     * {@code AiGenerationConfig} cannot end up with a different default here by omission.</p>
     *
     * <p>Not thread-safe, and not meant to be: a builder is filled and built on one thread, and the
     * {@link LlamaCppJniConfig} it produces is immutable.</p>
     */
    public static final class Builder {

        private final String modelPath;
        private int contextSize = AiGenerationConfig.DEFAULT_CONTEXT_SIZE;
        private int maxOutputTokens = AiGenerationConfig.DEFAULT_MAX_OUTPUT_TOKENS;
        private float temperature = AiGenerationConfig.DEFAULT_TEMPERATURE;
        private int threads = AiGenerationConfig.DEFAULT_THREADS;
        private float topP = AiGenerationConfig.DEFAULT_TOP_P;
        private int topK = AiGenerationConfig.DEFAULT_TOP_K;
        private float minP = AiGenerationConfig.DEFAULT_MIN_P;
        private float topNSigma = AiGenerationConfig.DEFAULT_TOP_N_SIGMA;
        private float repeatPenalty = AiGenerationConfig.DEFAULT_REPEAT_PENALTY;
        private @Nullable Boolean chatTemplateEnableThinking =
                AiGenerationConfig.DEFAULT_CHAT_TEMPLATE_ENABLE_THINKING;
        private boolean cachePrompt = AiGenerationConfig.DEFAULT_CACHE_PROMPT;
        private boolean swaFull = AiGenerationConfig.DEFAULT_SWA_FULL;
        private int cacheReuse = AiGenerationConfig.DEFAULT_CACHE_REUSE;
        private int gpuLayers = AiGenerationConfig.DEFAULT_GPU_LAYERS;
        private int seed = AiGenerationConfig.DEFAULT_SEED;
        private int cpuMoeLayers = AiGenerationConfig.DEFAULT_CPU_MOE_LAYERS;
        private int cpuFfnLayers = AiGenerationConfig.DEFAULT_CPU_FFN_LAYERS;
        private int kvUnifiedPerSlot = AiGenerationConfig.DEFAULT_KV_UNIFIED_PER_SLOT;
        private String lazyMode = AiGenerationConfig.DEFAULT_LAZY_MODE;
        private int repeatLastN = AiGenerationConfig.DEFAULT_REPEAT_LAST_N;
        private String cacheTypeK = AiGenerationConfig.DEFAULT_CACHE_TYPE_K;
        private String cacheTypeV = AiGenerationConfig.DEFAULT_CACHE_TYPE_V;
        private boolean flashAttn = AiGenerationConfig.DEFAULT_FLASH_ATTN;
        private int batchSize = AiGenerationConfig.DEFAULT_BATCH_SIZE;
        private int ubatchSize = AiGenerationConfig.DEFAULT_UBATCH_SIZE;
        private int threadsBatch = AiGenerationConfig.DEFAULT_THREADS_BATCH;
        private int mainGpu = AiGenerationConfig.DEFAULT_MAIN_GPU;
        private String devices = AiGenerationConfig.DEFAULT_DEVICES;
        private String reasoningEffort = AiGenerationConfig.DEFAULT_REASONING_EFFORT;
        private int reasoningBudgetTokens = AiGenerationConfig.DEFAULT_REASONING_BUDGET_TOKENS;
        private float dryMultiplier = AiGenerationConfig.DEFAULT_DRY_MULTIPLIER;
        private float dryBase = AiGenerationConfig.DEFAULT_DRY_BASE;
        private int dryAllowedLength = AiGenerationConfig.DEFAULT_DRY_ALLOWED_LENGTH;
        private int dryPenaltyLastN = AiGenerationConfig.DEFAULT_DRY_PENALTY_LAST_N;
        private List<String> drySequenceBreakers = Collections.<String>emptyList();
        private List<String> stopStrings = Collections.<String>emptyList();

        private Builder(final String modelPath) {
            this.modelPath = Objects.requireNonNull(modelPath, "modelPath");
        }

        /**
         * Sets context window size in tokens.
         *
         * @param contextSize context window size in tokens
         * @return this builder
         */
        public Builder contextSize(final int contextSize) {
            this.contextSize = contextSize;
            return this;
        }

        /**
         * Sets maximum number of output tokens per call.
         *
         * @param maxOutputTokens maximum number of output tokens per call
         * @return this builder
         */
        public Builder maxOutputTokens(final int maxOutputTokens) {
            this.maxOutputTokens = maxOutputTokens;
            return this;
        }

        /**
         * Sets sampling temperature.
         *
         * @param temperature sampling temperature
         * @return this builder
         */
        public Builder temperature(final float temperature) {
            this.temperature = temperature;
            return this;
        }

        /**
         * Sets number of CPU threads.
         *
         * @param threads number of CPU threads
         * @return this builder
         */
        public Builder threads(final int threads) {
            this.threads = threads;
            return this;
        }

        /**
         * Sets nucleus-sampling probability threshold.
         *
         * @param topP nucleus-sampling probability threshold
         * @return this builder
         */
        public Builder topP(final float topP) {
            this.topP = topP;
            return this;
        }

        /**
         * Sets top-k sampling limit.
         *
         * @param topK top-k sampling limit
         * @return this builder
         */
        public Builder topK(final int topK) {
            this.topK = topK;
            return this;
        }

        /**
         * Sets min-p sampling threshold ({@code 0.0} = disabled).
         *
         * @param minP min-p sampling threshold ({@code 0.0} = disabled)
         * @return this builder
         */
        public Builder minP(final float minP) {
            this.minP = minP;
            return this;
        }

        /**
         * Sets top-n-sigma sampling threshold ({@code -1.0} = disabled).
         *
         * @param topNSigma top-n-sigma sampling threshold ({@code -1.0} = disabled)
         * @return this builder
         */
        public Builder topNSigma(final float topNSigma) {
            this.topNSigma = topNSigma;
            return this;
        }

        /**
         * Sets repetition penalty.
         *
         * @param repeatPenalty repetition penalty
         * @return this builder
         */
        public Builder repeatPenalty(final float repeatPenalty) {
            this.repeatPenalty = repeatPenalty;
            return this;
        }

        /**
         * Sets the chat-template thinking mode.
         *
         * @param chatTemplateEnableThinking {@code true} or {@code false} to forward
         *        {@code enable_thinking} to the chat template, {@code null} to omit the kwarg
         * @return this builder
         */
        public Builder chatTemplateEnableThinking(final @Nullable Boolean chatTemplateEnableThinking) {
            this.chatTemplateEnableThinking = chatTemplateEnableThinking;
            return this;
        }

        /**
         * Sets whether llama.cpp prompt caching ({@code cache_prompt}) is enabled.
         *
         * @param cachePrompt whether llama.cpp prompt caching ({@code cache_prompt}) is enabled
         * @return this builder
         */
        public Builder cachePrompt(final boolean cachePrompt) {
            this.cachePrompt = cachePrompt;
            return this;
        }

        /**
         * Sets whether to keep the full-size SWA KV cache ({@code --swa-full}).
         *
         * @param swaFull whether to keep the full-size SWA KV cache ({@code --swa-full})
         * @return this builder
         */
        public Builder swaFull(final boolean swaFull) {
            this.swaFull = swaFull;
            return this;
        }

        /**
         * Sets kV prefix-reuse minimum chunk size ({@code --cache-reuse}); 0 = off.
         *
         * @param cacheReuse KV prefix-reuse minimum chunk size ({@code --cache-reuse}); 0 = off
         * @return this builder
         */
        public Builder cacheReuse(final int cacheReuse) {
            this.cacheReuse = cacheReuse;
            return this;
        }

        /**
         * Sets gPU layers to offload ({@code --gpu-layers}); -1 = leave default.
         *
         * @param gpuLayers GPU layers to offload ({@code --gpu-layers}); -1 = leave default
         * @return this builder
         */
        public Builder gpuLayers(final int gpuLayers) {
            this.gpuLayers = gpuLayers;
            return this;
        }

        /**
         * Sets rNG seed for generation; -1 = leave the random-per-request default.
         *
         * @param seed RNG seed for generation; -1 = leave the random-per-request default
         * @return this builder
         */
        public Builder seed(final int seed) {
            this.seed = seed;
            return this;
        }

        /**
         * Sets moE layers kept on the CPU ({@code --n-cpu-moe}); -1 = leave default.
         *
         * @param cpuMoeLayers MoE layers kept on the CPU ({@code --n-cpu-moe}); -1 = leave default
         * @return this builder
         */
        public Builder cpuMoeLayers(final int cpuMoeLayers) {
            this.cpuMoeLayers = cpuMoeLayers;
            return this;
        }

        /**
         * Sets fFN layers kept on the CPU ({@code --n-cpu-ffn}); -1 = leave default.
         *
         * @param cpuFfnLayers FFN layers kept on the CPU ({@code --n-cpu-ffn}); -1 = leave default
         * @return this builder
         */
        public Builder cpuFfnLayers(final int cpuFfnLayers) {
            this.cpuFfnLayers = cpuFfnLayers;
            return this;
        }

        /**
         * Sets per-slot unified KV context cap ({@code --kv-unified-per-slot}); -1 = leave default.
         *
         * @param kvUnifiedPerSlot per-slot unified KV context cap ({@code --kv-unified-per-slot}); -1 = leave default
         * @return this builder
         */
        public Builder kvUnifiedPerSlot(final int kvUnifiedPerSlot) {
            this.kvUnifiedPerSlot = kvUnifiedPerSlot;
            return this;
        }

        /**
         * Sets tensor-read laziness ({@code --tensor-read-lazy}); empty = leave default. {@code null} restores the default.
         *
         * @param lazyMode tensor-read laziness ({@code --tensor-read-lazy}); empty = leave default
         * @return this builder
         */
        public Builder lazyMode(final String lazyMode) {
            this.lazyMode = lazyMode != null ? lazyMode : AiGenerationConfig.DEFAULT_LAZY_MODE;
            return this;
        }

        /**
         * Sets the repeat-penalty window ({@code --repeat-last-n}); {@code -1} leaves llama.cpp's own.
         *
         * @param repeatLastN the repeat-penalty window ({@code --repeat-last-n}); {@code -1} leaves llama.cpp's own
         * @return this builder
         */
        public Builder repeatLastN(final int repeatLastN) {
            this.repeatLastN = repeatLastN;
            return this;
        }

        /**
         * Sets the KV-cache data type for K ({@code --cache-type-k}); empty leaves the default. {@code null} restores the default.
         *
         * @param cacheTypeK the KV-cache data type for K ({@code --cache-type-k}); empty leaves the default
         * @return this builder
         */
        public Builder cacheTypeK(final String cacheTypeK) {
            this.cacheTypeK = cacheTypeK != null ? cacheTypeK : AiGenerationConfig.DEFAULT_CACHE_TYPE_K;
            return this;
        }

        /**
         * Sets the KV-cache data type for V ({@code --cache-type-v}); empty leaves the default. {@code null} restores the default.
         *
         * @param cacheTypeV the KV-cache data type for V ({@code --cache-type-v}); empty leaves the default
         * @return this builder
         */
        public Builder cacheTypeV(final String cacheTypeV) {
            this.cacheTypeV = cacheTypeV != null ? cacheTypeV : AiGenerationConfig.DEFAULT_CACHE_TYPE_V;
            return this;
        }

        /**
         * Sets whether Flash Attention is enabled ({@code --flash-attn}).
         *
         * @param flashAttn whether Flash Attention is enabled ({@code --flash-attn})
         * @return this builder
         */
        public Builder flashAttn(final boolean flashAttn) {
            this.flashAttn = flashAttn;
            return this;
        }

        /**
         * Sets the logical batch size ({@code --batch-size}); {@code -1} leaves the default.
         *
         * @param batchSize the logical batch size ({@code --batch-size}); {@code -1} leaves the default
         * @return this builder
         */
        public Builder batchSize(final int batchSize) {
            this.batchSize = batchSize;
            return this;
        }

        /**
         * Sets the physical batch size ({@code --ubatch-size}); {@code -1} leaves the default.
         *
         * @param ubatchSize the physical batch size ({@code --ubatch-size}); {@code -1} leaves the default
         * @return this builder
         */
        public Builder ubatchSize(final int ubatchSize) {
            this.ubatchSize = ubatchSize;
            return this;
        }

        /**
         * Sets the batch/prompt-processing thread count ({@code --threads-batch}); {@code -1} reuses {@code threads}.
         *
         * @param threadsBatch the batch/prompt-processing thread count ({@code --threads-batch}); {@code -1} reuses {@code threads}
         * @return this builder
         */
        public Builder threadsBatch(final int threadsBatch) {
            this.threadsBatch = threadsBatch;
            return this;
        }

        /**
         * Sets primary GPU index ({@code --main-gpu}); -1 = leave default.
         *
         * @param mainGpu primary GPU index ({@code --main-gpu}); -1 = leave default
         * @return this builder
         */
        public Builder mainGpu(final int mainGpu) {
            this.mainGpu = mainGpu;
            return this;
        }

        /**
         * Sets device selection ({@code --device}); empty = leave default. {@code null} restores the default.
         *
         * @param devices device selection ({@code --device}); empty = leave default
         * @return this builder
         */
        public Builder devices(final String devices) {
            this.devices = devices != null ? devices : AiGenerationConfig.DEFAULT_DEVICES;
            return this;
        }

        /**
         * Sets gpt-oss reasoning-effort kwarg value ("low"/"medium"/"high"); empty omits it. {@code null} restores the default.
         *
         * @param reasoningEffort gpt-oss reasoning-effort kwarg value ("low"/"medium"/"high"); empty omits it
         * @return this builder
         */
        public Builder reasoningEffort(final String reasoningEffort) {
            this.reasoningEffort =
                    reasoningEffort != null ? reasoningEffort : AiGenerationConfig.DEFAULT_REASONING_EFFORT;
            return this;
        }

        /**
         * Sets reasoning/think-token budget ({@code -1} = unrestricted).
         *
         * @param reasoningBudgetTokens reasoning/think-token budget ({@code -1} = unrestricted)
         * @return this builder
         */
        public Builder reasoningBudgetTokens(final int reasoningBudgetTokens) {
            this.reasoningBudgetTokens = reasoningBudgetTokens;
            return this;
        }

        /**
         * Sets dRY sampling multiplier ({@code 0.0} = disabled).
         *
         * @param dryMultiplier DRY sampling multiplier ({@code 0.0} = disabled)
         * @return this builder
         */
        public Builder dryMultiplier(final float dryMultiplier) {
            this.dryMultiplier = dryMultiplier;
            return this;
        }

        /**
         * Sets dRY base (effective only when {@code dryMultiplier > 0}).
         *
         * @param dryBase DRY base (effective only when {@code dryMultiplier > 0})
         * @return this builder
         */
        public Builder dryBase(final float dryBase) {
            this.dryBase = dryBase;
            return this;
        }

        /**
         * Sets dRY allowed length (effective only when {@code dryMultiplier > 0}).
         *
         * @param dryAllowedLength DRY allowed length (effective only when {@code dryMultiplier > 0})
         * @return this builder
         */
        public Builder dryAllowedLength(final int dryAllowedLength) {
            this.dryAllowedLength = dryAllowedLength;
            return this;
        }

        /**
         * Sets the DRY penalty look-back window in tokens ({@code -1} = not sent, {@code 0} = off).
         *
         * @param dryPenaltyLastN DRY penalty look-back tokens ({@code -1} = not sent, so llama.cpp keeps
         *                        its own window; {@code 0} = off)
         * @return this builder
         */
        public Builder dryPenaltyLastN(final int dryPenaltyLastN) {
            this.dryPenaltyLastN = dryPenaltyLastN;
            return this;
        }

        /**
         * Sets dRY sequence breakers; may be {@code null} (treated as empty → binding default). {@code null} restores the empty default.
         *
         * @param drySequenceBreakers DRY sequence breakers; may be {@code null} (treated as empty → binding default)
         * @return this builder
         */
        public Builder drySequenceBreakers(final List<String> drySequenceBreakers) {
            this.drySequenceBreakers =
                    drySequenceBreakers != null ? drySequenceBreakers : Collections.<String>emptyList();
            return this;
        }

        /**
         * Sets stop strings; may be {@code null} (treated as empty). {@code null} restores the empty default.
         *
         * @param stopStrings stop strings; may be {@code null} (treated as empty)
         * @return this builder
         */
        public Builder stopStrings(final List<String> stopStrings) {
            this.stopStrings = stopStrings != null ? stopStrings : Collections.<String>emptyList();
            return this;
        }

        /**
         * Builds the immutable configuration.
         *
         * @return the configuration
         */
        public LlamaCppJniConfig build() {
            return new LlamaCppJniConfig(this);
        }
    }
}
