// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.srcmorph.provider;

import java.io.IOException;
import java.util.Map;
import java.util.Objects;
import lombok.ToString;
import net.ladenthin.llama.LlamaModel;
import net.ladenthin.llama.args.FlashAttn;
import net.ladenthin.llama.args.ReasoningFormat;
import net.ladenthin.llama.json.ChatResponseParser;
import net.ladenthin.llama.parameters.ModelParameters;
import net.ladenthin.llama.value.ChatResponse;
import net.ladenthin.llama.value.Timings;
import net.ladenthin.srcmorph.document.AiGenerationRequest;
import net.ladenthin.srcmorph.prompt.AiPromptSupport;
import net.ladenthin.srcmorph.support.Java8CompatibilityHelper;
import org.jspecify.annotations.Nullable;

/**
 * {@link AiGenerationProvider} implementation backed by the {@code net.ladenthin:llama}
 * JNI binding, running GGUF models locally via llama.cpp.
 *
 * <p>{@code toString} is generated by Lombok over the configuration and prompt-support
 * fields for build-log diagnostics. The native {@link LlamaModel} handle is excluded
 * from the rendered output because its default {@code toString} prints implementation
 * details (native pointer, internal state) that are noisy and not useful for
 * Maven-side debugging.
 */
@ToString
public final class LlamaCppJniAiGenerationProvider implements AiGenerationProvider, AutoCloseable {

    private final LlamaCppJniConfig config;

    // Native llama.cpp model handle — its toString prints native pointer / internal
    // state details; excluded from the rendered output. Lazily initialised on first
    // generate() so constructing the provider (via the factory, or when every file is
    // already cached) is cheap and native-free; the ~90 MB GGUF + native context are
    // only loaded when generation actually happens.
    @ToString.Exclude
    private @Nullable LlamaModel model;

    private final AiPromptSupport promptSupport;

    /**
     * Everything this provider does that does not touch the native handle. Split out so the
     * mutation gate can reach it: see {@link LlamaCppJniProviderSupport}'s own javadoc for why
     * the boundary runs where it does.
     */
    @ToString.Exclude
    private final LlamaCppJniProviderSupport support;

    private final AiCompletionParser completionParser = new AiCompletionParser();
    private final ChatResponseParser chatResponseParser = new ChatResponseParser();
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    /**
     * Creates a new {@link LlamaCppJniAiGenerationProvider}; the GGUF model is loaded lazily on the first generate(...) call.
     *
     * @param config        llama.cpp configuration
     * @param promptSupport prompt lookup used to render request prompts
     */
    public LlamaCppJniAiGenerationProvider(final LlamaCppJniConfig config, final AiPromptSupport promptSupport) {
        this.config = Objects.requireNonNull(config, "config");
        this.promptSupport = Objects.requireNonNull(promptSupport, "promptSupport");
        this.support = new LlamaCppJniProviderSupport(this.config, this.promptSupport);
    }

    /** Loads the GGUF model on first use and caches it for subsequent calls. */
    private LlamaModel model() {
        LlamaModel current = model;
        if (current == null) {
            final Map<String, String> chatTemplateKwargs = support.buildChatTemplateKwargs();
            final ModelParameters modelParameters = new ModelParameters()
                    .setModel(config.modelPath())
                    .setCtxSize(config.contextSize())
                    .setThreads(config.threads())
                    // Parse reasoning channels (Qwen <think>, gpt-oss harmony analysis) into
                    // reasoning_content so message content stays clean (final channel only).
                    .setReasoningFormat(ReasoningFormat.AUTO)
                    .setChatTemplateKwargs(chatTemplateKwargs);
            // Keep the full-size SWA KV cache so the sliding-window layers' KV is reusable across
            // files (restores prompt-prefix reuse for gpt-oss), at the cost of more KV RAM.
            if (config.swaFull()) {
                modelParameters.enableSwaFull();
            }
            // Enable cross-request KV prefix reuse (min chunk size in tokens) when configured.
            if (config.cacheReuse() > 0) {
                modelParameters.setCacheReuse(config.cacheReuse());
            }
            // Offload model layers to the GPU when explicitly configured (>= 0). -1 leaves the
            // binding/native-build default (CPU build stays CPU; GPU build uses its own default).
            if (config.gpuLayers() >= 0) {
                modelParameters.setGpuLayers(config.gpuLayers());
            }
            // Keep the MoE expert weights of the first n layers on the CPU. Unlike --gpu-layers this
            // moves only the expert weights (the bulk of a MoE model), so a much larger model fits the
            // same VRAM at a smaller speed cost. 0 is meaningful ("keep none on the CPU"), so the guard
            // is >= 0; -1 leaves the binding/native-build default.
            if (config.cpuMoeLayers() >= 0) {
                modelParameters.setCpuMoeLayers(config.cpuMoeLayers());
            }
            // Dense-model counterpart of --n-cpu-moe: keep the FFN weights of the first n layers on the
            // CPU. Same >= 0 guard and same "0 is meaningful" reasoning.
            if (config.cpuFfnLayers() >= 0) {
                modelParameters.setCpuFfnLayers(config.cpuFfnLayers());
            }
            // Cap the unified KV context budget per slot. The binding rejects 0 and negatives, so only
            // a positive value is forwarded; -1 leaves the binding/native-build default.
            if (config.kvUnifiedPerSlot() > 0) {
                modelParameters.setKvUnifiedPerSlot(config.kvUnifiedPerSlot());
            }
            // Read lazy-loadable tensors on demand instead of keeping them resident. Shortens model
            // load time, which matters here because a run loads one model per model group and
            // calibrate preflights every model in turn. Empty leaves the binding/native-build default.
            if (!compatibilityHelper.isBlank(config.lazyMode())) {
                modelParameters.setLazyMode(LlamaCppJniProviderSupport.lazyMode(config.lazyMode()));
            }
            // Flash Attention. Emitted only when asked for: llama.cpp's own default is `auto`, so
            // NOT emitting the option leaves it to decide per backend and model, which is what an
            // unconfigured run should get. `--flash-attn` takes a mandatory on|off|auto value, which
            // is why this goes through the enum setter -- the bare-flag setter emits the key alone
            // and llama.cpp then swallows the following argv token.
            if (config.flashAttn()) {
                modelParameters.setFlashAttn(FlashAttn.ON);
            }
            // KV-cache quantization. Set independently of each other, but note that a quantized V cache
            // generally needs Flash Attention above -- llama.cpp refuses the combination otherwise.
            if (!compatibilityHelper.isBlank(config.cacheTypeK())) {
                modelParameters.setCacheTypeK(LlamaCppJniProviderSupport.cacheType("cacheTypeK", config.cacheTypeK()));
            }
            if (!compatibilityHelper.isBlank(config.cacheTypeV())) {
                modelParameters.setCacheTypeV(LlamaCppJniProviderSupport.cacheType("cacheTypeV", config.cacheTypeV()));
            }
            // Prefill sizing. The binding's own default for both is 0, which llama.cpp reads as
            // "decide for me", so 0 is not a meaningful user value and the guard is > 0.
            if (config.batchSize() > 0) {
                modelParameters.setBatchSize(config.batchSize());
            }
            if (config.ubatchSize() > 0) {
                modelParameters.setUbatchSize(config.ubatchSize());
            }
            if (config.threadsBatch() > 0) {
                modelParameters.setThreadsBatch(config.threadsBatch());
            }
            // Pick a specific GPU when configured (>= 0). Matters on multi-GPU hosts: a Vulkan build
            // enumerates every GPU (an integrated GPU may be device 0), so the default can select the
            // slower one. -1 leaves the binding/native-build default.
            if (config.mainGpu() >= 0) {
                modelParameters.setMainGpu(config.mainGpu());
            }
            // Explicit device selection (comma-separated backend device names, e.g. "Vulkan1") takes
            // precedence over a single main-GPU index. Empty leaves the binding/native-build default.
            if (!config.devices().isEmpty()) {
                modelParameters.setDevices(config.devices());
            }
            current = new LlamaModel(modelParameters);
            model = current;
        }
        return current;
    }

    @Override
    public String generate(final AiGenerationRequest request) throws IOException {
        final ChatResponse response = chatResponse(request);
        support.warnOnTruncatedAnswer(request, response);
        support.logPromptCacheReuse(request, response);
        return completionParser.parseCompletion(response.getFirstContent());
    }

    /**
     * Runs one chat completion and parses the whole response.
     *
     * <p>This is the same native call {@code chatCompleteText(...)} makes underneath &mdash; that method is
     * literally {@code extractChoiceContent(chatComplete(...))} &mdash; so parsing the full response here
     * costs no extra inference. What it buys is everything the text-only accessor throws away: the finish
     * reason (is the answer complete?), the token usage, and the KV-cache counters.</p>
     *
     * @param request the generation request
     * @return the parsed response
     */
    private ChatResponse chatResponse(final AiGenerationRequest request) {
        return chatResponseParser.parseResponse(model().chatComplete(support.buildInferenceParameters(request)));
    }

    // Narrows away the interface's checked IOException: the chat path (chatComplete + parse) throws only
    // unchecked exceptions, so declaring IOException here would be bogus (BED).
    @Override
    public AiGenerationTimings generateWithTimings(final AiGenerationRequest request) {
        // chatComplete(...) returns the full OpenAI-compatible JSON, which the server populates with a
        // "timings" object (prompt_n / predicted_n / prompt_per_second / predicted_per_second) for every
        // real generation. chatCompleteText(...) discards it; here we parse it into a ChatResponse and
        // surface the model's OWN measured throughput (no chars/token estimate).
        final ChatResponse response = chatResponse(request);
        final String text = response.getFirstContent();
        final Timings timings = response.getTimings();
        if (timings == null) {
            // A build/response without timings degrades to zero rates so the caller's fallback can act.
            return new AiGenerationTimings(text, 0, 0, 0.0d, 0, 0.0d);
        }
        // cache_n is the leading prompt slice llama.cpp served straight from the KV cache. It is the only
        // observable the prefix-reuse settings (cachePrompt / cacheReuse / swaFull) produce, so it is
        // surfaced rather than dropped: without it a run pays swaFull's KV memory on faith.
        return new AiGenerationTimings(
                text,
                (int) timings.getPromptN(),
                timings.getCacheN(),
                timings.getPromptPerSecond(),
                (int) timings.getPredictedN(),
                timings.getPredictedPerSecond());
    }

    @Override
    public void close() {
        final LlamaModel current = model;
        if (current != null) {
            current.close();
        }
    }
}
