// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.srcmorph.provider;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import lombok.ToString;
import net.ladenthin.llama.LlamaModel;
import net.ladenthin.llama.args.CacheType;
import net.ladenthin.llama.args.ReasoningFormat;
import net.ladenthin.llama.args.TensorReadLazyMode;
import net.ladenthin.llama.json.ChatResponseParser;
import net.ladenthin.llama.parameters.InferenceParameters;
import net.ladenthin.llama.parameters.ModelParameters;
import net.ladenthin.llama.value.ChatResponse;
import net.ladenthin.llama.value.Pair;
import net.ladenthin.llama.value.Timings;
import net.ladenthin.srcmorph.document.AiGenerationRequest;
import net.ladenthin.srcmorph.prompt.AiPromptSupport;
import net.ladenthin.srcmorph.support.Java8CompatibilityHelper;
import org.jspecify.annotations.Nullable;

/**
 * {@link AiGenerationProvider} implementation backed by the {@code net.ladenthin:llama}
 * JNI binding, running GGUF models locally via llama.cpp.
 *
 * <p>{@code toString} is generated by Lombok over the configuration and prompt-support
 * fields for build-log diagnostics. The native {@link LlamaModel} handle is excluded
 * from the rendered output because its default {@code toString} prints implementation
 * details (native pointer, internal state) that are noisy and not useful for
 * Maven-side debugging.
 */
@ToString
public final class LlamaCppJniAiGenerationProvider implements AiGenerationProvider, AutoCloseable {

    private final LlamaCppJniConfig config;

    // Native llama.cpp model handle — its toString prints native pointer / internal
    // state details; excluded from the rendered output. Lazily initialised on first
    // generate() so constructing the provider (via the factory, or when every file is
    // already cached) is cheap and native-free; the ~90 MB GGUF + native context are
    // only loaded when generation actually happens.
    @ToString.Exclude
    private @Nullable LlamaModel model;

    private final AiPromptSupport promptSupport;
    private final AiCompletionParser completionParser = new AiCompletionParser();
    private final ChatResponseParser chatResponseParser = new ChatResponseParser();
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    /**
     * Fixed llama.cpp server slot every request is pinned to. The model is loaded once and reused
     * for all files; pinning each request to the same slot lets the prompt cache
     * ({@code cache_prompt}) reuse the shared prompt-template prefix's KV across files instead of
     * re-prefilling it for every file. Reuse is exact, so generated output is unchanged.
     */
    private static final int REUSE_SLOT_ID = 0;

    /** Chat-template kwarg controlling Qwen-style thinking (ignored by non-Qwen templates). */
    private static final String ENABLE_THINKING_KWARG = "enable_thinking";

    /** Chat-template kwarg for the gpt-oss reasoning-effort level (ignored by non-gpt-oss templates). */
    private static final String REASONING_EFFORT_KWARG = "reasoning_effort";

    /** Number of chat-template kwargs put into the map (used for presizing). */
    private static final int CHAT_TEMPLATE_KWARG_COUNT = 2;

    /**
     * Creates a new {@link LlamaCppJniAiGenerationProvider}; the GGUF model is loaded lazily on the first generate(...) call.
     *
     * @param config        llama.cpp configuration
     * @param promptSupport prompt lookup used to render request prompts
     */
    public LlamaCppJniAiGenerationProvider(final LlamaCppJniConfig config, final AiPromptSupport promptSupport) {
        this.config = Objects.requireNonNull(config, "config");
        this.promptSupport = Objects.requireNonNull(promptSupport, "promptSupport");
    }

    /** Loads the GGUF model on first use and caches it for subsequent calls. */
    private LlamaModel model() {
        LlamaModel current = model;
        if (current == null) {
            final Map<String, String> chatTemplateKwargs =
                    new HashMap<>(compatibilityHelper.hashMapCapacityFor(CHAT_TEMPLATE_KWARG_COUNT));
            chatTemplateKwargs.put(ENABLE_THINKING_KWARG, String.valueOf(config.chatTemplateEnableThinking()));
            // gpt-oss honors reasoning_effort; non-gpt-oss chat templates ignore it. An empty
            // configured value omits the kwarg so the model's own template default applies.
            if (!compatibilityHelper.isBlank(config.reasoningEffort())) {
                chatTemplateKwargs.put(REASONING_EFFORT_KWARG, config.reasoningEffort());
            }
            final ModelParameters modelParameters = new ModelParameters()
                    .setModel(config.modelPath())
                    .setCtxSize(config.contextSize())
                    .setThreads(config.threads())
                    // Parse reasoning channels (Qwen <think>, gpt-oss harmony analysis) into
                    // reasoning_content so message content stays clean (final channel only).
                    .setReasoningFormat(ReasoningFormat.AUTO)
                    .setChatTemplateKwargs(chatTemplateKwargs);
            // Keep the full-size SWA KV cache so the sliding-window layers' KV is reusable across
            // files (restores prompt-prefix reuse for gpt-oss), at the cost of more KV RAM.
            if (config.swaFull()) {
                modelParameters.enableSwaFull();
            }
            // Enable cross-request KV prefix reuse (min chunk size in tokens) when configured.
            if (config.cacheReuse() > 0) {
                modelParameters.setCacheReuse(config.cacheReuse());
            }
            // Offload model layers to the GPU when explicitly configured (>= 0). -1 leaves the
            // binding/native-build default (CPU build stays CPU; GPU build uses its own default).
            if (config.gpuLayers() >= 0) {
                modelParameters.setGpuLayers(config.gpuLayers());
            }
            // Keep the MoE expert weights of the first n layers on the CPU. Unlike --gpu-layers this
            // moves only the expert weights (the bulk of a MoE model), so a much larger model fits the
            // same VRAM at a smaller speed cost. 0 is meaningful ("keep none on the CPU"), so the guard
            // is >= 0; -1 leaves the binding/native-build default.
            if (config.cpuMoeLayers() >= 0) {
                modelParameters.setCpuMoeLayers(config.cpuMoeLayers());
            }
            // Dense-model counterpart of --n-cpu-moe: keep the FFN weights of the first n layers on the
            // CPU. Same >= 0 guard and same "0 is meaningful" reasoning.
            if (config.cpuFfnLayers() >= 0) {
                modelParameters.setCpuFfnLayers(config.cpuFfnLayers());
            }
            // Cap the unified KV context budget per slot. The binding rejects 0 and negatives, so only
            // a positive value is forwarded; -1 leaves the binding/native-build default.
            if (config.kvUnifiedPerSlot() > 0) {
                modelParameters.setKvUnifiedPerSlot(config.kvUnifiedPerSlot());
            }
            // Read lazy-loadable tensors on demand instead of keeping them resident. Shortens model
            // load time, which matters here because a run loads one model per model group and
            // calibrate preflights every model in turn. Empty leaves the binding/native-build default.
            if (!compatibilityHelper.isBlank(config.tensorReadLazy())) {
                modelParameters.setTensorReadLazy(tensorReadLazyMode(config.tensorReadLazy()));
            }
            if (config.flashAttn()) {
                modelParameters.enableFlashAttn();
            }
            // KV-cache quantization. Set independently of each other, but note that a quantized V cache
            // generally needs Flash Attention above -- llama.cpp refuses the combination otherwise.
            if (!compatibilityHelper.isBlank(config.cacheTypeK())) {
                modelParameters.setCacheTypeK(cacheType("cacheTypeK", config.cacheTypeK()));
            }
            if (!compatibilityHelper.isBlank(config.cacheTypeV())) {
                modelParameters.setCacheTypeV(cacheType("cacheTypeV", config.cacheTypeV()));
            }
            // Prefill sizing. The binding's own default for both is 0, which llama.cpp reads as
            // "decide for me", so 0 is not a meaningful user value and the guard is > 0.
            if (config.batchSize() > 0) {
                modelParameters.setBatchSize(config.batchSize());
            }
            if (config.ubatchSize() > 0) {
                modelParameters.setUbatchSize(config.ubatchSize());
            }
            if (config.threadsBatch() > 0) {
                modelParameters.setThreadsBatch(config.threadsBatch());
            }
            // Pick a specific GPU when configured (>= 0). Matters on multi-GPU hosts: a Vulkan build
            // enumerates every GPU (an integrated GPU may be device 0), so the default can select the
            // slower one. -1 leaves the binding/native-build default.
            if (config.mainGpu() >= 0) {
                modelParameters.setMainGpu(config.mainGpu());
            }
            // Explicit device selection (comma-separated backend device names, e.g. "Vulkan1") takes
            // precedence over a single main-GPU index. Empty leaves the binding/native-build default.
            if (!config.devices().isEmpty()) {
                modelParameters.setDevices(config.devices());
            }
            current = new LlamaModel(modelParameters);
            model = current;
        }
        return current;
    }

    /**
     * Resolves a configured {@code --tensor-read-lazy} value to the binding's enum.
     *
     * <p>Matched case-insensitively against the CLI strings the enum itself declares
     * ({@code off}, {@code auto}, {@code on}), so this never drifts from the binding. An
     * unrecognised value is rejected rather than silently ignored: it is always a configuration
     * typo, and dropping it would hand the user a run that quietly did not do what was asked.</p>
     *
     * <p>Package-private rather than private so it can be unit-tested without loading a model: it is
     * otherwise reachable only from the lazy {@code model()} path, which needs a real GGUF.</p>
     *
     * @param value the configured value; must not be blank (callers guard on that)
     * @return the matching mode
     * @throws IllegalArgumentException if no mode declares that CLI string
     */
    static TensorReadLazyMode tensorReadLazyMode(final String value) {
        for (final TensorReadLazyMode mode : TensorReadLazyMode.values()) {
            if (mode.getArgValue().equalsIgnoreCase(value)) {
                return mode;
            }
        }
        throw new IllegalArgumentException("Invalid tensorReadLazy value: \"" + value + "\" (expected one of: "
                + knownTensorReadLazyValues() + ")");
    }

    /**
     * Resolves a configured {@code --cache-type-k} / {@code --cache-type-v} value to the binding's enum.
     *
     * <p>Same contract as {@link #tensorReadLazyMode(String)}: matched case-insensitively against the CLI
     * strings the enum itself declares, so a cache type upstream adds is accepted for free, and an
     * unrecognised value is rejected rather than dropped. The knob name is passed in so the message names
     * the element the user actually wrote.</p>
     *
     * @param knobName the configuration element name, for the error message
     * @param value    the configured value; must not be blank (callers guard on that)
     * @return the matching cache type
     * @throws IllegalArgumentException if no cache type declares that CLI string
     */
    static CacheType cacheType(final String knobName, final String value) {
        for (final CacheType type : CacheType.values()) {
            if (type.getArgValue().equalsIgnoreCase(value)) {
                return type;
            }
        }
        throw new IllegalArgumentException(
                "Invalid " + knobName + " value: \"" + value + "\" (expected one of: " + knownCacheTypeValues() + ")");
    }

    /**
     * Renders the accepted KV-cache types for an error message.
     *
     * @return the CLI strings the binding's enum declares, comma-separated in declaration order
     */
    private static String knownCacheTypeValues() {
        final StringBuilder known = new StringBuilder();
        for (final CacheType type : CacheType.values()) {
            if (known.length() > 0) {
                known.append(", ");
            }
            known.append(type.getArgValue());
        }
        return known.toString();
    }

    /**
     * Renders the accepted {@code --tensor-read-lazy} values for an error message.
     *
     * @return the CLI strings the binding's enum declares, comma-separated in declaration order
     */
    private static String knownTensorReadLazyValues() {
        final StringBuilder known = new StringBuilder();
        for (final TensorReadLazyMode mode : TensorReadLazyMode.values()) {
            if (known.length() > 0) {
                known.append(", ");
            }
            known.append(mode.getArgValue());
        }
        return known.toString();
    }

    @Override
    public String generate(final AiGenerationRequest request) throws IOException {
        return completionParser.parseCompletion(model().chatCompleteText(buildInferenceParameters(request)));
    }

    // Narrows away the interface's checked IOException: the chat path (chatComplete + parse) throws only
    // unchecked exceptions, so declaring IOException here would be bogus (BED).
    @Override
    public AiGenerationTimings generateWithTimings(final AiGenerationRequest request) {
        // chatComplete(...) returns the full OpenAI-compatible JSON, which the server populates with a
        // "timings" object (prompt_n / predicted_n / prompt_per_second / predicted_per_second) for every
        // real generation. chatCompleteText(...) discards it; here we parse it into a ChatResponse and
        // surface the model's OWN measured throughput (no chars/token estimate).
        final ChatResponse response =
                chatResponseParser.parseResponse(model().chatComplete(buildInferenceParameters(request)));
        final String text = response.getChoices().isEmpty()
                ? ""
                : response.getChoices().get(0).getMessage().getContent();
        final Timings timings = response.getTimings();
        if (timings == null) {
            // A build/response without timings degrades to zero rates so the caller's fallback can act.
            return new AiGenerationTimings(text, 0, 0, 0.0d, 0, 0.0d);
        }
        // cache_n is the leading prompt slice llama.cpp served straight from the KV cache. It is the only
        // observable the prefix-reuse settings (cachePrompt / cacheReuse / swaFull) produce, so it is
        // surfaced rather than dropped: without it a run pays swaFull's KV memory on faith.
        return new AiGenerationTimings(
                text,
                (int) timings.getPromptN(),
                timings.getCacheN(),
                timings.getPromptPerSecond(),
                (int) timings.getPredictedN(),
                timings.getPredictedPerSecond());
    }

    /**
     * Builds the immutable {@link InferenceParameters} for the given request from the resolved config.
     *
     * @param request the generation request
     * @return the inference parameters
     */
    private InferenceParameters buildInferenceParameters(final AiGenerationRequest request) {
        // Static instructions go in the SYSTEM message (byte-identical across files, so its KV
        // prefix is reused by cache_prompt); the variable file name + source go in the USER message.
        final String systemPrompt = promptSupport.systemPrompt(request.promptKey());
        final String userMessage = promptSupport.userMessage(request.sourceFile(), request.sourceText());

        final List<Pair<String, String>> messages = new ArrayList<>();
        messages.add(new Pair<>("user", userMessage));

        // InferenceParameters uses immutable withers: each with* returns a new instance, so the
        // whole request is built as a single chain.
        final InferenceParameters baseParameters = new InferenceParameters("")
                .withMessages(systemPrompt, messages)
                .withTemperature(config.temperature())
                .withNPredict(config.maxOutputTokens())
                .withTopP(config.topP())
                .withTopK(config.topK())
                .withMinP(config.minP())
                .withTopNSigma(config.topNSigma())
                .withRepeatPenalty(config.repeatPenalty())
                // Cap harmony analysis (reasoning) tokens so a runaway chain-of-thought cannot
                // starve the final answer; -1 (default) = unrestricted, so behaviour is unchanged.
                .withReasoningBudgetTokens(config.reasoningBudgetTokens())
                // DRY (Don't Repeat Yourself) repetition suppression; multiplier 0.0 (default) = off,
                // so the base/allowed-length/penalty-last-n knobs have no effect unless opted in.
                .withDryMultiplier(config.dryMultiplier())
                .withDryBase(config.dryBase())
                .withDryAllowedLength(config.dryAllowedLength())
                .withDryPenaltyLastN(config.dryPenaltyLastN())
                .withStopStrings(config.stopStrings().toArray(new String[0]))
                // Keep the shared prompt-template prefix warm in the KV cache and reuse it across
                // files (pinned to one slot); only the differing source is re-prefilled.
                // Reuse is exact -> output unchanged.
                .withCachePrompt(config.cachePrompt())
                .withSlotId(REUSE_SLOT_ID);

        // Pin the RNG seed only when explicitly configured (>= 0). Upstream's default is a random seed
        // per request, so an unconfigured run keeps exactly the behaviour it had; a configured one makes
        // the generated body stable for a given machine and configuration, which is what turns a
        // re-index into a reviewable diff. Not bit-reproducibility -- see AiGenerationConfig.DEFAULT_SEED.
        final InferenceParameters seededParameters =
                config.seed() >= 0 ? baseParameters.withSeed(config.seed()) : baseParameters;

        // The window the repeat penalty above acts on. Forwarded only when configured (>= 0), so an
        // unconfigured run keeps llama.cpp's own window; 0 is meaningful (disables the penalty), and the
        // binding rejects negatives, which is why the guard is >= 0 rather than > 0.
        final InferenceParameters penaltyScopedParameters =
                config.repeatLastN() >= 0 ? seededParameters.withRepeatLastN(config.repeatLastN()) : seededParameters;

        // Only override the DRY sequence breakers when explicitly configured; an empty list keeps
        // the binding/model default set instead of clearing it.
        return config.drySequenceBreakers().isEmpty()
                ? penaltyScopedParameters
                : penaltyScopedParameters.withDrySequenceBreakers(
                        config.drySequenceBreakers().toArray(new String[0]));
    }

    @Override
    public void close() {
        final LlamaModel current = model;
        if (current != null) {
            current.close();
        }
    }
}
